name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node modules
        run: |
          npm install

      - name: Run test
        run: |
          npm run test
